=== NOAA-OWP/DMOD/python/lib/evaluations/dmod/evaluations/specification/schema/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "observations": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "address": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "backend": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "format": {
                  "type": "string"
                },
                "properties": {
                  "type": "object"
                }
              },
              "required": [
                "type",
                "format"
              ]
            },
            "locations": {
              "type": "object",
              "properties": {
                "identify": {
                  "type": "boolean"
                },
                "from": {
                  "type": "string"
                },
                "pattern": {
                  "type": "string"
                },
                  "ids": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                "identify"
              ]
            },
            "field_mapping": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string"
                    },
                    "mapType": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "field",
                    "mapType",
                    "value"
                  ]
                }
              ]
            }
          },
          "required": [
            "address",
            "name",
            "backend"
          ]
        }
      ]
    },
    "predictions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "address": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "backend": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "format": {
                  "type": "string"
                },
                "properties": {
                  "type": "object"
                }
              },
              "required": [
                "type",
                "format"
              ]
            },
            "locations": {
              "type": "object",
              "properties": {
                "identify": {
                  "type": "boolean"
                },
                "from": {
                  "type": "string"
                },
                "pattern": {
                  "type": "string"
                },
                  "ids": {
                      "type": "array",
                      "items": {
                          "type": "string"
                      }
                  }
              },
              "required": [
                "identify"
              ]
            },
            "field_mapping": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string"
                    },
                    "mapType": {
                      "type": "string"
                    },
                    "value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "field",
                    "mapType",
                    "value"
                  ]
                }
              ]
            }
          },
          "required": [
            "address",
            "name",
            "backend"
          ]
        }
      ]
    },
    "crosswalks": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "format": {
              "type": "string"
            },
            "address": {
              "type": "string"
            },
            "prediction_fields": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string"
                    },
                    "path": {
                      "type": ["array", "null"],
                      "items": [
                        {
                          "type": "string"
                        }
                      ]
                    }
                  },
                  "required": [
                    "field"
                  ]
                }
              ]
            },
            "observation_fields": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "field": {
                      "type": "string"
                    },
                    "path": {
                      "type": "array",
                      "items": [
                        {
                          "type": "string"
                        }
                      ]
                    }
                  },
                  "required": [
                    "field"
                  ]
                }
              ]
            }
          },
          "required": [
            "type",
            "format",
            "address",
            "prediction_fields",
            "observation_fields"
          ]
        }
      ]
    },
    "thresholds": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "address": {
              "type": "string"
            },
            "backend": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string"
                },
                "format": {
                  "type": "string"
                },
                  "properties": {
                      "type": "array",
                      "items": {
                          "type": "object"
                      }
                  }
              },
              "required": [
                "type",
                "format"
              ]
            },
            "locations": {
              "type": "object",
              "properties": {
                "identify": {
                  "type": "boolean"
                },
                "from": {
                  "type": "string"
                },
                "pattern": {
                  "type": "string"
                }
              },
              "required": [
                "identify"
              ]
            },
            "definitions": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "field": {
                      "type": "string"
                    },
                      "weight": {
                        "type": "number"
                      }
                  },
                  "required": [
                    "name",
                    "field",
                      "weight"
                  ]
                }
              ]
            }
          },
          "required": [
            "address",
            "backend",
            "definitions"
          ]
        }
      ]
    },
    "scheme": {
      "type": "object",
      "properties": {
        "metrics": {
          "type": "array",
            "minItems": 1,
            "uniqueItems": true,
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "weight": {
                  "type": "integer"
                },
                  "properties": {
                      "type": "array",
                      "items": {
                          "type": "object"
                      }
                  }
              },
              "required": [
                "name",
                "weight"
              ]
            }
          ]
        }
      },
      "required": [
        "metrics"
      ]
    }
  },
  "required": [
    "observations",
    "predictions",
    "crosswalks",
    "thresholds",
    "scheme"
  ]
}

=== NOAA-OWP/DMOD/python/gui/static/resources/evaluation_template.json
{
    "observations": [
        {
            "name": "Observations",
            "value_field": "observation",
            "value_selectors": [
                {
                    "name": "observation",
                    "where": "value",
                    "path": ["values[*]", "value[*]", "value"],
                    "datatype": "float",
                    "origin": ["$", "value", "timeSeries[*]"],
                    "associated_fields": [
                        {
                            "name":"value_date",
                            "path": ["values[*]", "value[*]", "dateTime"],
                            "datatype": "datetime"
                        },
                        {
                            "name":"observation_location",
                            "path": ["sourceInfo", "siteCode", "[0]", "value"],
                            "datatype": "string"
                        },
                        {
                            "name":"unit",
                            "path": ["variable", "unit", "unitCode"],
                            "datatype": "string"
                        }
                    ]
                }
            ],
            "backend": {
                "backend_type": "file",
                "data_format": "json",
                "address": "path/to/observations.json"
            },
            "locations": {
                "identify": "true",
                "from_field": "value"
            },
            "unit": {
                "field": "unit"
            },
            "x_axis": "value_date"
        }
    ],
    "predictions": [
        {
            "name": "Predictions",
            "value_field": "prediction",
            "value_selectors": [
                {
                    "name": "predicted",
                    "where": "column",
                    "associated_fields": [
                        {
                            "name": "date",
                            "datatype": "datetime"
                        }
                    ]
                }
            ],
            "backend": {
                "backend_type": "file",
                "data_format": "csv",
                "address": "path/to/cat.*cfs.csv",
                "parse_dates": ["date"]
            },
            "locations": {
                "identify": "true",
                "from_field": "filename",
                "pattern": "cat-\\d\\d"
            },
            "field_mapping": [
                {
                    "field": "prediction",
                    "map_type": "column",
                    "value": "predicted"
                },
                {
                    "field": "prediction_location",
                    "map_type": "column",
                    "value": "location"
                },
                {
                    "field": "value_date",
                    "map_type": "column",
                    "value": "date"
                }
            ],
            "unit": {
                "value": "ft^3/s"
            },
            "x_axis": "value_date"
        }
    ],
    "crosswalks": [
        {
            "backend": {
                "backend_type": "file",
                "address": "path/to/crosswalk.json",
                "data_format": "json"
            },
            "observation_field_name": "observation_location",
            "prediction_field_name": "prediction_location",
            "field": {
                "name": "prediction_location",
                "where": "key",
                "path": ["* where site_no"],
                "origin": "$",
                "datatype": "string",
                "associated_fields": [
                    {
                        "name": "observation_location",
                        "path": "site_no",
                        "datatype": "string"
                    }
                ]
            }
        }
    ],
    "thresholds": [
        {
            "backend": {
                "backend_type": "file",
                "data_format": "rdb",
                "address": "path/to/stat_thresholds.rdb"
            },
            "locations": {
                "identify": "true",
                "from_field": "column",
                "pattern": "site_no"
            },
            "application_rules": {
                "threshold_field": {
                    "name": "threshold_day",
                    "path": [
                        "month_nu",
                        "day_nu"
                    ],
                    "datatype": "Day"
                },
                "observation_field": {
                    "name": "threshold_day",
                    "path": [
                        "value_date"
                    ],
                    "datatype": "Day"
                }
            },
            "definitions": [
                {
                    "name": "75th Percentile",
                    "field": "p75_va",
                    "weight": 10,
                    "unit": {
                        "value": "ft^3/s"
                    }
                }
            ]
        },
        {
            "backend": {
                "backend_type": "file",
                "data_format": "json",
                "address": "path/to/thresholds.json"
            },
            "locations": {
                "identify": "true",
                "from_field": "value",
                "pattern": "metadata/usgs_site_code"
            },
            "origin": "$.value_set[?(@.calc_flow_values.rating_curve.id_type == 'NWS Station')]",
            "definitions": [
                {
                    "name": "Action",
                    "field": "calc_flow_values/action",
                    "weight": 3,
                    "unit": {
                        "path": "metadata/calc_flow_units"
                    }
                },
                {
                    "name": "Flood",
                    "field": "calc_flow_values/flood",
                    "weight": 2,
                    "unit": {
                        "path": "metadata/calc_flow_units"
                    }
                }
            ]
        }
    ],
    "scheme": {
        "metrics": [
            {
                "name": "False Alarm Ratio",
                "weight": 10
            },
            {
                "name": "Probability of Detection",
                "weight": 10
            },
            {
                "name": "Kling-Gupta Efficiency",
                "weight": 15
            },
            {
                "name": "Normalized Nash-Sutcliffe Efficiency",
                "weight": 15
            },
            {
                "name": "Pearson Correlation Coefficient",
                "weight": 18
            }
        ]
    }
}

=== NOAA-OWP/DMOD/python/lib/evaluations/dmod/test/resources/merge.part_b.json
{
    "observations": [
        {
            "value_selectors": [
                {
                    "name": "observation",
                    "where": "value",
                    "path": ["values[*]", "value[*]", "value"],
                    "datatype": "float",
                    "origin": ["$", "value", "timeSeries[*]"],
                    "associated_fields": [
                        {
                            "name":"unit",
                            "path": ["variable", "unit", "unitCode"],
                            "datatype": "string"
                        }
                    ]
                }
            ],
            "backend": {
                "backend_type": "file",
                "format": "json",
                "address": "resources/observations.json"
            },
            "locations": {
                "identify": true,
                "from_field": "value"
            },
            "unit": {
                "field": "unit"
            },
            "x_axis": "value_date"
        }
    ],
    "predictions": [
        {
            "name": "Predictions",
            "value_field": "prediction",
            "value_selectors": [
                {
                    "name": "predicted",
                    "where": "column",
                    "associated_fields": [
                        {
                            "name": "date",
                            "datatype": "datetime"
                        }
                    ]
                }
            ],
            "backend": {
                "backend_type": "file",
                "format": "csv",
                "address": "resources/cat.*cfs.csv",
                "parse_dates": ["date"]
            },
            "locations": {
                "identify": true,
                "from_field": "filename",
                "pattern": "cat-\\d\\d"
            },
            "field_mapping": [
                {
                    "field": "prediction_location",
                    "map_type": "column",
                    "value": "location"
                },
                {
                    "field": "value_date",
                    "map_type": "column",
                    "value": "date"
                }
            ],
            "x_axis": "value_date"
        }
    ],
    "crosswalks": [
        {
            "name": "Crosswalk",
            "observation_field_name": "observation_location",
            "prediction_field_name": "prediction_location",
            "field": {
                "name": "prediction_location",
                "where": "key",
                "path": ["* where site_no"],
                "origin": "$",
                "datatype": "string",
                "associated_fields": [
                    {
                        "name": "observation_location",
                        "path": "site_no",
                        "datatype": "string"
                    }
                ]
            }
        }
    ],
    "thresholds": [
        {
            "name": "NWIS Stat Percentiles",
            "backend": {
                "name": "NWIS Stat Thresholds",
                "backend_type": "file",
                "format": "rdb",
                "address": "resources/nwis_stat_thresholds.rdb"
            },
            "application_rules": {
                "name": "Date to Day",
                "threshold_field": {
                    "name": "threshold_day",
                    "path": [
                        "month_nu",
                        "day_nu"
                    ],
                    "datatype": "Day"
                },
                "observation_field": {
                    "name": "threshold_day",
                    "path": [
                        "value_date"
                    ],
                    "datatype": "Day"
                }
            },
            "definitions": [
                {
                    "name": "Median",
                    "field": "p50_va",
                    "weight": 1,
                    "unit": {
                        "value": "ft^3/s"
                    }
                }
            ]
        }
    ],
    "scheme": {
        "name": "Prefer Pearson, then Nash and Kling, then POD and FAR",
        "metrics": [
            {
                "name": "Normalized Nash-Sutcliffe Efficiency",
                "weight": 15
            },
            {
                "name": "Pearson Correlation Coefficient",
                "weight": 18
            }
        ]
    }
}
